using EntityViews.SourceGenerators.FormsGeneration;

namespace EntityViews.SourceGenerators.Templates.Maui;

public class MauiEntryPropertyTemplate
{
    public static string Build(InputTemplateParams p)
    {
        return @$"// <auto-generated/>
#nullable enable

{MauiGenerator.GetUsingStatements(p)}

namespace {p.FormNamespace};

public class {p.Property.Name}Input : {p.BaseControlClassName ?? "EntityViews.Input.EntityViewsTextInput"}
{{
    public {p.Property.Name}Input()
    {{
        Input{MauiGenerator.GetBindingExpression("Entry.TextProperty", p)}

        Initialized(""{p.Property.Name}"", {p.PropertyDisplaySource});
    }}
}}
";
    }
}
