namespace EntityViews.SourceGenerators.Templates.Maui;

public class MauiDatePickerPropertyTemplate
{
    public static string Build(InputTemplateParams p)
    {
        var property = p.Property;
        var viewModelName = p.ViewModelName;
        var viewModelNamespace = p.ViewModelNamespace;
        var formNamespace = p.FormNamespace;
        var propertyDisplaySource = p.PropertyDisplaySource;

        return @$"// <auto-generated/>
#nullable enable

using CommunityToolkit.Maui.Markup;
using {viewModelNamespace};

namespace {formNamespace};

public class {property.Name}Input : {p.BaseControlClassName ?? "EntityViews.Input.EntityViewsDatePickerInput"}
{{
    public {property.Name}Input()
    {{
        Input.BackgroundColor = Colors.Transparent;

        Input
            .Bind(
                DatePicker.DateProperty,
                getter: static ({viewModelName} vm) => vm.{property.Name},
                setter: static ({viewModelName} vm, {property.Type.Name} value) => vm.{property.Name} = value);        

        Initialized(""{property.Name}"", {propertyDisplaySource});
    }}

    public override void Initialized(string propertyName, string? displayName)
    {{
        base.Initialized(propertyName, displayName);

        Transform(
            true,
            new(0, 0, AbsoluteLayout.AutoSize, AbsoluteLayout.AutoSize),
            .7,
            new(5, 0),
            new(0.5f, 1, 0, HighlightBorderHeight),
            1);
    }}
}}
";
    }
}
