namespace EntityViews.SourceGenerators.Templates.Maui;

public class MauiEditorPropertyTemplate
{
    public static string Build(InputTemplateParams p)
    {
        var property = p.Property;
        var viewModelName = p.ViewModelName;
        var viewModelNamespace = p.ViewModelNamespace;
        var formNamespace = p.FormNamespace;
        var propertyDisplaySource = p.PropertyDisplaySource;

        return @$"// <auto-generated/>
#nullable enable

using CommunityToolkit.Maui.Markup;
using {viewModelNamespace};

namespace {formNamespace};

public class {property.Name}Input : {p.BaseControlClassName ?? "EntityViews.Input.EntityViewsTextAreaInput"}
{{
    public {property.Name}Input()
    {{
        Label.Text({propertyDisplaySource});

        Input
            .Bind(
                Editor.TextProperty,
                getter: static ({viewModelName} vm) => vm.{property.Name},
                setter: static ({viewModelName} vm, {property.Type.Name} value) => vm.{property.Name} = value);
        Input.Triggers.Add(
            new DataTrigger(typeof(Editor))
            {{
                Binding = new Binding(""{property.Name}HasError""),
                Value = true,
                Setters = {{ new Setter {{ Property = BackgroundColorProperty, Value = {_MauiDefaultInputs.OnErrorBackgroundColor} }} }},
            }});
        async Task<bool> UserKeepsTyping()
        {{
            var txt = Input.Text;
            await Task.Delay(500);
            return txt != Input.Text;
        }}
        Input.TextChanged += async (_, _) =>
        {{
            if (await UserKeepsTyping()) return;
            (({viewModelName})BindingContext).ValidateDirtyProperty(
                ""{property.Name}"", Input.Text is not null && Input.Text.Length > 0);
        }};

        ValidationLabel
            .Bind(
                Label.TextProperty,
                getter: static ({viewModelName} vm) => vm.{property.Name}Error);
    }}
}}
";
    }
}
