using EntityViews.SourceGenerators.FormsGeneration;

namespace EntityViews.SourceGenerators.Templates.Maui;

public class MauiSliderPropertyTemplate
{
    public static string Build(InputTemplateParams p)
    {
        return @$"// <auto-generated/>
#nullable enable

{MauiGenerator.GetUsingStatements(p)}

namespace {p.FormNamespace};

public class {p.Property.Name}Input : {p.BaseControlClassName ?? "Slider"}
{{
    public {p.Property.Name}Input()
    {{
        this{MauiGenerator.GetBindingExpression("Slider.ValueProperty", p)}
    }}
}}
";
    }
}
