using Microsoft.CodeAnalysis;

namespace EntityViews.SourceGenerators.Templates;

public class MauiFormTemplate
{
    public static string Build(
        Compilation compilation,
        string viewModelName,
        string viewModelNamespace,
        string formNamespace,
        IPropertySymbol property)
    {
        return @$"// <auto-generated/>
    #nullable enable

    using CommunityToolkit.Maui.Markup;
    using {viewModelNamespace};

    namespace {formNamespace};

    public class {property.Name}Input : StackLayout
    {{
        public {property.Name}Input()
        {{
            var label = new Label().Text(""{property.Name}"");

            var entry = new Entry().Bind(Entry.TextProperty,
                getter: static ({viewModelName} vm) => vm.{property.Name},
                setter: static ({viewModelName} vm, {property.Type.Name} value) => vm.{property.Name} = value);
            entry.Triggers.Add(
                new DataTrigger(typeof(Entry))
                {{
                    Binding = new Binding(""{property.Name}HasError""),
                    Value = true,
                    Setters = {{ new Setter {{ Property = BackgroundColorProperty, Value = Colors.Red }} }},
                }});

            var validationLabel = new Label().Bind(Label.TextProperty,
                getter: static ({viewModelName} vm) => vm.{property.Name}Error);

            Children.Add(label);
            Children.Add(entry);
            Children.Add(validationLabel);
        }}
    }}

";
    }
}
