namespace EntityViews.SourceGenerators.Templates.Input;

public class MauiEditorPropertyTemplate
{
    public static string Build(InputTemplateParams p)
    {
        var property = p.Property;
        var viewModelName = p.ViewModelName;
        var viewModelNamespace = p.ViewModelNamespace;
        var formNamespace = p.FormNamespace;
        var propertyDisplaySource = p.PropertyDisplaySource;

        return @$"// <auto-generated/>
#nullable enable

using CommunityToolkit.Maui.Markup;
using {viewModelNamespace};

namespace {formNamespace};

public class {property.Name}Input : StackLayout
{{
    public {property.Name}Input()
    {{
        var label = new Label().Text({propertyDisplaySource});

        var input = new Editor()
            .Bind(
                Editor.TextProperty,
                getter: static ({viewModelName} vm) => vm.{property.Name},
                setter: static ({viewModelName} vm, {property.Type.Name} value) => vm.{property.Name} = value);
        input.Triggers.Add(
            new DataTrigger(typeof(Editor))
            {{
                Binding = new Binding(""{property.Name}HasError""),
                Value = true,
                Setters = {{ new Setter {{ Property = BackgroundColorProperty, Value = Colors.Red }} }},
            }});
        async Task<bool> UserKeepsTyping()
        {{
            var txt = input.Text;
            await Task.Delay(500);
            return txt != input.Text;
        }}
        input.TextChanged += async (_, _) =>
        {{
            if (await UserKeepsTyping()) return;
            (({viewModelName})BindingContext).ValidateDirtyProperty(
                ""{property.Name}"", input.Text is not null && input.Text.Length > 0);
        }};

        var validationLabel = new Label()
            .Bind(
                Label.TextProperty,
                getter: static ({viewModelName} vm) => vm.{property.Name}Error);

        Children.Add(label);
        Children.Add(input);
        Children.Add(validationLabel);
    }}
}}
";
    }
}
