namespace EntityViews.SourceGenerators.Templates.Input;

public class MauiSwitchPropertyTemplate
{
    public static string Build(InputTemplateParams p)
    {
        var property = p.Property;
        var viewModelName = p.ViewModelName;
        var viewModelNamespace = p.ViewModelNamespace;
        var formNamespace = p.FormNamespace;
        var propertyDisplaySource = p.PropertyDisplaySource;

        return @$"// <auto-generated/>
#nullable enable

using CommunityToolkit.Maui.Markup;
using {viewModelNamespace};

namespace {formNamespace};

public class {property.Name}Input : StackLayout
{{
    public {property.Name}Input()
    {{
        var label = new Label().Text({propertyDisplaySource});

        var input = new Switch()
            .Bind(
                Switch.IsToggledProperty,
                getter: static ({viewModelName} vm) => vm.{property.Name},
                setter: static ({viewModelName} vm, bool value) => vm.{property.Name} = value);

        var validationLabel = new Label()
            .Bind(
                Label.TextProperty,
                getter: static (ToDoViewModel vm) => vm.IsDone);

        Children.Add(label);
        Children.Add(input);
        Children.Add(validationLabel);
    }}
}}
";
    }
}
